### ISSUE TITLE
Being able to press the save button if in draft mode

### ISSUE THREAD

**Issue by felskia** [map-egypt/admin#87]
I feel like we used to have this and so I don't know what happened. When in draft mode, if all of the required fields aren't entered in, the user should still be able to save the information.

**Comment by kamicut** [comment]
@felskia This is still set up, although it doesn't work for some fields. For example, you can save in draft mode without adding a budget. 

The issue is that the text fields (for example project name, objective) are captured by the _browser's_ native HTML validation rather than the library. 

One way I could take another stab at this is by replacing the string fields with a special widget which goes around the native HTML validation.

**Comment by felskia** [comment]
@kamicut right now there are so many that you can't get away with not filling out almost the whole form which makes it seem like the functionality isn't there at all. Anything you can do to fix this would be appreciated
